Cast password as string
Fixes:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 37, in main
        exit(synchronize(config))
      File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 93, in synchronize
        ldapconn = ldap.connect(**config['ldap'])
      File "/usr/local/lib/python3.5/dist-packages/ldap2pg/ldap.py", line 309, in connect
        conn.simple_bind_s(options['BINDDN'], options['PASSWORD'])
      File "/usr/local/lib/python3.5/dist-packages/ldap2pg/ldap.py", line 257, in simple_bind_s
        return self.wrapped.simple_bind_s(binddn, password)
      File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 454, in simple_bind_s
        msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
      File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 448, in simple_bind
        return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
      File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 324, in _ldap_call
        result = func(*args,**kwargs)
    TypeError: a bytes-like object is required, not 'int'