Always decode LDAP value
Actually, pyldap only decode attributes and well-known value. For now, we decode
all values, systematically. This should not break base64 attributes.

Fixes:

    Found role b'dba' from cn cn=dba,ou=groups,dc=ldap,dc=ldap2pg,dc=docker.
    Role b'dba' must have members alan, albert, alice.
    ...
    Unhandled error:
    Traceback (most recent call last):
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/script.py", line 75, in main
        exit(wrapped_main(config))
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/script.py", line 55, in wrapped_main
        count = manager.sync(*sync_data)
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 321, in sync
        for query in expandqueries(queries, databases):
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/psql.py", line 127, in expandqueries
        for query in queries:
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 287, in diff
        for role in missing.flatten():
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/role.py", line 199, in flatten
        for name in sorted(index.keys()):
    TypeError: unorderable types: bytes() < str()