Require name in role rule
Fixes:

    Unhandled error:
    Traceback (most recent call last):
      File ".../ldap2pg/script.py", line 75, in main
        exit(wrapped_main(config))
      File ".../ldap2pg/script.py", line 50, in wrapped_main
        syncmap=config['sync_map'])
      File ".../ldap2pg/manager.py", line 254, in inspect
        for role in self.apply_role_rules(mapping['roles'], entries):
      File ".../ldap2pg/manager.py", line 170, in apply_role_rules
        for role in self.process_ldap_entry(entry=entry, **rule):
      File ".../ldap2pg/manager.py", line 132, in process_ldap_entry
        name_attribute = kw['name_attribute']
    KeyError: 'name_attribute'