rpm: Always rebuild sdist along rpm
This avoid using old sdist built with the wrong python version.

Fixes:

    Error: Package: ldap2pg-3.2-1.el6.noarch (/ldap2pg-3.2-1.el6.noarch)
               Requires: python(abi) = 2.6
               Installed: python-2.7.5-58.el7.x86_64 (@base)
                   python(abi) = 2.7
                   python(abi) = 2.7
               Available: python34-3.4.5-4.el7.x86_64 (epel)
                   python(abi) = 3.4