Restore debug mode
Fixes:

    [ldap2pg.script      DEBUG] Dropping in debugger.
    > /usr/lib64/python2.7/site-packages/ldap/ldapobject.py(99)_ldap_call()
    -> result = func(*args,**kwargs)
    (Pdb) Traceback (most recent call last):
      File "/usr/bin/ldap2pg", line 11, in <module>
        load_entry_point('ldap2pg==1.0', 'console_scripts', 'ldap2pg')()
      File "/workspace/ldap2pg/script.py", line 80, in main
        pdb.post_mortem(sys.exc_info()[2])
      File "/usr/lib64/python2.7/pdb.py", line 1267, in post_mortem
        p.interaction(None, t)
      File "/usr/lib64/python2.7/pdb.py", line 210, in interaction
        self.cmdloop()
      File "/usr/lib64/python2.7/cmd.py", line 130, in cmdloop
        line = raw_input(self.prompt)
    ValueError: I/O operation on closed file