Ignore spurious ldapsearch arguments
This makes ldap2pg future proof and avoid trackback with typo.

Fixes:

    Unhandled error:
    Traceback (most recent call last):
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/script.py", line 37, in main
        exit(synchronize(config))
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/script.py", line 129, in synchronize
        count = manager.sync(syncmap=config['sync_map'])
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 292, in sync
        ldaproles, ldapacl = self.inspect_ldap(syncmap)
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 162, in inspect_ldap
        entries = self.query_ldap(**mapping['ldap'])
    TypeError: query_ldap() missing 1 required positional argument: 'attributes'