Manage SQL error in roles_query
Fixes:

   Unhandled error:
    Traceback (most recent call last):
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/script.py", line 75, in main
        exit(wrapped_main(config))
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/script.py", line 50, in wrapped_main
        syncmap=config['sync_map'])
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 269, in inspect
        schemas, pgowners, pgroles, pgacls = self.inspect_pg(syncmap)
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 195, in inspect_pg
        pgroles = RoleSet(self.process_pg_roles(rows))
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/role.py", line 161, in __init__
        super(RoleSet, self).__init__(*a, **kw)
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 71, in process_pg_roles
        for row in rows:
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/manager.py", line 67, in fetch_pg_roles
        for row in psql(qry):
      File "/home/bersace/src/dalibo/ldap2pg/ldap2pg/psql.py", line 87, in __call__
        self.cursor.execute(query, *args)
    psycopg2.ProgrammingError: column role.canlogin does not exist
    LINE 8: WHERE role.rolname LIKE 'd%' AND role.canlogin
                                             ^
    HINT:  Perhaps you meant to reference the column "role.rolcanlogin".